name: MDQ Store - Cuarentena

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar scraper MDQ
        run: |
          python mdq.py

      - name: Guardar resultados
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add catalogo_cuarentena/mdq.csv
          git add catalogo_cuarentena/mdq.log.txt

          git diff --cached --quiet || git commit -m "Actualizar MDQ Store"

          git push
