name: ABC Gaming Scraper

on:
  workflow_dispatch:        # botón manual en GitHub
  schedule:
    - cron: "0 8 * * *"    # también corre automático cada día a las 8 AM UTC
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360    # máximo 6 horas

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install pandas openpyxl beautifulsoup4 lxml playwright requests
          playwright install chromium
          playwright install-deps chromium

      - name: Correr scraper
        run: python scraper.py

- name: Guardar Excel actualizado
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git add .

        git commit -m "Excel actualizado automatico" || echo "Sin cambios"

        git push

      - name: Subir Excel como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: catalogo-abc-gaming
          path: catalogo_completo_abc_gaming.xlsx
          retention-days: 30    # disponible para descargar por 30 días

